### ISSUE TITLE
spider cocoon in the broodmother encounter is setting player hp to 1 when popped. Possibly have to do with 7.30 venomancer changes

### ISSUE THREAD

**Issue by ArcadiaReduxAutomation** [arcadia-redux/pathfinders#11] opened 2021-08-20 10:16 UTC
Opened from Discord by **FRIDAY#8768**
Follow the conversation [here](https://discord.com/channels/501306949434867713/876970971007971358/878220908991492157)

**Comment by fcalife** [comment] 2021-09-01 01:21
Duplicate of https://github.com/arcadia-redux/pathfinders/issues/16

**Closed by fcalife** 2021-09-01 01:21 UTC
Labels: bug
